# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'index.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Index_Form(object):
    def setupUi(self, Index_Form):
        Index_Form.setObjectName("Index_Form")
        Index_Form.resize(1070, 640)
        self.tableView = QtWidgets.QTableView(Index_Form)
        self.tableView.setGeometry(QtCore.QRect(20, 140, 1021, 441))
        self.tableView.setObjectName("tableView")
        self.label = QtWidgets.QLabel(Index_Form)
        self.label.setGeometry(QtCore.QRect(10, 20, 1021, 31))
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(Index_Form)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 70, 1021, 51))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.SSE100I = QtWidgets.QPushButton(self.layoutWidget)
        self.SSE100I.setObjectName("SSE100I")
        self.horizontalLayout_2.addWidget(self.SSE100I)
        self.SSEIN = QtWidgets.QPushButton(self.layoutWidget)
        self.SSEIN.setObjectName("SSEIN")
        self.horizontalLayout_2.addWidget(self.SSEIN)
        self.SSECS = QtWidgets.QPushButton(self.layoutWidget)
        self.SSECS.setObjectName("SSECS")
        self.horizontalLayout_2.addWidget(self.SSECS)
        self.SSETC = QtWidgets.QPushButton(self.layoutWidget)
        self.SSETC.setObjectName("SSETC")
        self.horizontalLayout_2.addWidget(self.SSETC)
        self.SSEINT = QtWidgets.QPushButton(self.layoutWidget)
        self.SSEINT.setObjectName("SSEINT")
        self.horizontalLayout_2.addWidget(self.SSEINT)
        self.SSEEN = QtWidgets.QPushButton(self.layoutWidget)
        self.SSEEN.setObjectName("SSEEN")
        self.horizontalLayout_2.addWidget(self.SSEEN)
        self.SSEHC = QtWidgets.QPushButton(self.layoutWidget)
        self.SSEHC.setObjectName("SSEHC")
        self.horizontalLayout_2.addWidget(self.SSEHC)
        self.SSENR = QtWidgets.QPushButton(self.layoutWidget)
        self.SSENR.setObjectName("SSENR")
        self.horizontalLayout_2.addWidget(self.SSENR)
        self.SSEMT = QtWidgets.QPushButton(self.layoutWidget)
        self.SSEMT.setObjectName("SSEMT")
        self.horizontalLayout_2.addWidget(self.SSEMT)
        self.SSEFN = QtWidgets.QPushButton(self.layoutWidget)
        self.SSEFN.setObjectName("SSEFN")
        self.horizontalLayout_2.addWidget(self.SSEFN)
        self.label_5 = QtWidgets.QLabel(Index_Form)
        self.label_5.setGeometry(QtCore.QRect(30, 600, 1021, 31))
        self.label_5.setObjectName("label_5")

        self.retranslateUi(Index_Form)
        QtCore.QMetaObject.connectSlotsByName(Index_Form)

    def retranslateUi(self, Index_Form):
        _translate = QtCore.QCoreApplication.translate
        Index_Form.setWindowTitle(_translate("Index_Form", "Form"))
        self.label.setText(_translate("Index_Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">View indices by industry sector</span></p></body></html>"))
        self.SSE100I.setText(_translate("Index_Form", "Composite"))
        self.SSEIN.setText(_translate("Index_Form", "Industrial"))
        self.SSECS.setText(_translate("Index_Form", "Consumer"))
        self.SSETC.setText(_translate("Index_Form", "Telecom Business"))
        self.SSEINT.setText(_translate("Index_Form", "Information"))
        self.SSEEN.setText(_translate("Index_Form", "Energy"))
        self.SSEHC.setText(_translate("Index_Form", "Pharmaceutical"))
        self.SSENR.setText(_translate("Index_Form", "Natural Resources"))
        self.SSEMT.setText(_translate("Index_Form", "Raw Materials"))
        self.SSEFN.setText(_translate("Index_Form", "Financial and Real Estate"))
        self.label_5.setText(_translate("Index_Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Note: All index data are from the Shanghai Stock Exchange</span></p></body></html>"))
